### PR TITLE
Make hack.af serverless

### PR DESCRIPTION
**Pull request by zanedb**
This PR makes hack.af use [Vercel Serverless](https://vercel.com/docs/serverless-functions/introduction), instead of Express/a server.

Note: requires hackclub/airbridge#30 to be merged.

### CODE REVIEW

**Comment by itsmingjie** [comment]
Thanks for making my shitty code better <3

**Comment by lachlanjc** [comment]
0BD6FAE2-D708-4631-B8FC-59DF6F34E565
https://hackaf-git-fork-zanedb-serverless.hackclub.dev/som-stickers isn’t working for me :/

**Comment by zanedb** [comment]
Yep, Vercel is deploying from the hackclub/hack.af serverless branch instead of zanedb/hack.af's of the same name. Try it here: https://hack-af.vercel.app/som-stickers

**Comment by zanedb** [comment]
(Also, could you double check that the clicks field in Airtable is being updated properly? :)

**Comment by lachlanjc** [comment]
Ok, awesome. Will try to review with Max on Monday.

**Comment by maxwofford** [comment]
@lachlanjc cool if we just merge this now & toss the link in #sink-my-ship?

**Comment by lachlanjc** [comment]
Go for it. I didn't super closely read the code or check Airtable's logs but

**Comment by itsmingjie** [comment]
🎉

**Pull request merged**
