### PR TITLE
Migrate to TypeScript, Postgres and Prisma

### PR DESCRIPTION
**Pull request by KhushrajRathod**
## To do:
- [ ] Create production database
- [ ] Migrate records to production database

## Changes:
- Migrate from Airtable to Heroku Postgres + Prisma
- Migrate from JavaScript to TypeScript
- Remove useless dependencies
- Add missing code to count link views

### CODE REVIEW

**Comment by sampoder** [comment]
Hmm.... just my two cents here: this makes it very painful to create a new record for someone who is non technical. Unless... I'm missing something maybe.

Like with Airtable it's super super easy, not sure what's the alternative here

**Comment by KhushrajRathod** [comment]
@sampoder See https://hackclub.slack.com/archives/C0C78SG9L/p1611837226187100?thread_ts=1611780978.144200&cid=C0C78SG9L

**Comment by sampoder** [comment]
Hmmm... seems interesting

**Review by cfanoulis — CHANGES_REQUESTED** [review]
Hi, I'm against this. This just induces unnecessary cost, and requires a lot of UIs that airtable just provides

Also see https://hackclub.slack.com/archives/C0C78SG9L/p1614622137239400?thread_ts=1614622137.239400&cid=C0C78SG9L

**Comment by KhushrajRathod** [comment]
> This just induces unnecessary cost

How so? This reduces the cost, Heroku Postgres is free up to 10K records, as compared to the 1,200 free records provided by Airtable

> requires a lot of UIs that airtable just provides

Which UI specifically? Pgweb provides editing of records (and much, much, more, of course), and that's all that is required

**Comment by cfanoulis** [comment]
So we have 10k records on another service, instead of the 50k records hack club already pays for. Also, consider the time cost of someone having to tend over a db (which is brought uo every time you mention prisma)

pgweb can't even compare to the airtable UI. On one, you have to search a non-mobile-friendly dashboard, on the other you just fill out a form, or head to the native app

**Comment by KhushrajRathod** [comment]
> Also, consider the time cost of someone having to tend over a db (which is brought uo every time you mention prisma)

I don't get what you mean by tend over a db. Databases are not something that constantly break without human intervention.

> pgweb can't even compare to the airtable UI. On one, you have to search a non-mobile-friendly dashboard, on the other you just fill out a form, or head to the native app

Sure. You have a variety of native postgres apps for both iOS and Android. Feel free to pick one you like

**Comment by itsmingjie** [comment]
Hey all, long time no see 👋 I want to weigh in as the original shitty hacker who hacked the v0 of this in 30 minutes -- (briefly glanced at the thread in Slack earlier)

The reason why hack.af is created is that Hack Club needed a tool that technical **and non-technical** staff. Currently, the flow for creating a new redirection link is no different than filling out an Airtable form (it is staff only and is as simple as "slug", "URL", "description (optional)"). Any staff can easily create a link by navigating to hack.af/new as long as they are authenticated under the Hack Club domain. 

From what I read, I don't think that need has changed. Unless something is fundamentally broken, I don't think any overengineering is necessary on this front. Creating a piece of software requires maintenance, and at this moment, this is a piece of software that required minimum engineering time to maintain (esp. after @zanedb's rewrite to serverless). Moving it to something else will not only create unnecessary problems but will also inevitably over-complicate the process. 

That being said though, I really respect those who are actively trying to create and improve software for Hack Club. But with that, I also have concerns -- consider the implications of these "migrations" as we are dealing with a massive amount of student PII-data -- you might want to have HQ staff on-board with you before you start working on anything. Although, I could be working with limited information here given I haven't been on HC Slack for half a year.

**Comment by itsmingjie** [comment]
Closing due to inactivity. If there are further discussions about this, feel free to reopen!

**Pull request closed without merging**
